version: '3.8'

services:
  postgres:
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  # Local Jupyter environment
  jupyter-local:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: jupyter-local
    restart: unless-stopped
    depends_on:
      - postgres
      - redis
    environment:
      - POSTGRES_HOST=postgres
      - REDIS_HOST=redis
      - JUPYTER_ENABLE_LAB=yes
      - JUPYTER_TOKEN=local_secure_token_2024
      - SPORTMONKS_API_KEY=${SPORTMONKS_API_KEY}
    ports:
      - "8888:8888"
    volumes:
      - .:/workspace
      - jupyter_data:/home/jovyan/.jupyter

  # pgAdmin for database management
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin-local
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - "8080:80"

volumes:
  postgres_data:
  redis_data:
  jupyter_data:
  pgadmin_data:

networks:
  default:
    name: soccer-intelligence-local
