# Essential API Keys Configuration for Manchester City Soccer Intelligence System
# Core configuration for data collection APIs
# NEVER commit api_keys.yaml to version control

# ============================================================================
# Primary Soccer Data APIs
# ============================================================================

# API-Football Configuration (Primary Data Source)
api_football:
  key: "5ced20dec7f4b2226c8944c88c6d86aa"
  base_url: "https://v3.football.api-sports.io"
  rate_limit: 75000
  timeout: 30
  retry_attempts: 3
  retry_delay: 1.0

# SportMonks API Configuration (Enhanced Data Source)
sportmonks:
  api_key: "rhcvz5smy1FKTKqaEI1kbuhJlAZLADDHQvvDquOHbpDsjfHbwE6OxP5MMS4p"
  base_url: "https://api.sportmonks.com/v3"
  rate_limit: 3000
  timeout: 30
  retry_attempts: 3
  retry_delay: 1.0

# ============================================================================
# Database Configuration
# ============================================================================
database:
  host: "localhost"
  port: 5432
  name: "soccer_intelligence"
  user: "soccerapp"
  password: "soccerpass123"

# ============================================================================
# Redis Cache Configuration
# ============================================================================
redis:
  host: "localhost"
  port: 6379
  password: "redispass123"
  db: 0

# ============================================================================
# Manchester City Team Configuration
# ============================================================================
manchester_city:
  team_id_sportmonks: 496
  team_id_api_football: 50
  team_name: "Manchester City"
  seasons_focus: ["2023-2024"]
  competitions:
    - "Premier League"
    - "UEFA Champions League"
    - "FA Cup"
    - "EFL Cup"
