# API Keys Configuration
# This file contains your actual API keys and is ignored by git

# API-Football Configuration
api_football:
  key: "5ced20dec7f4b2226c8944c88c6d86aa"
  # Get your key from: https://dashboard.api-football.com

# OpenAI Configuration  
openai:
  api_key: "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"
  # Get your key from: https://platform.openai.com/api-keys

# Twitter API Configuration (Optional)
twitter:
  bearer_token: "AAAAAAAAAAAAAAAAAAAAAMxW2wEAAAAAt%2Fdt%2B2j%2B4Ldaf7%2FTZ5T1PUqJ6DM%3DJexHIP8AB7vdpfPMllp93Rtsij8fI5pYvnPCZUrSoDYpFq62tP"
  access_token: "1939468647472496641-zx5sdjp0pZdYn4ZzCFvcRQJDi9OjV9"
  access_token_secret: "kZX90z5dq2whG3qfDL2YVoLAn853hnRuLPTVV4VHalEGW"
  api_key: "T12OsO6Be5sl8yn4SN0p3xdyP"
  api_key_secret: "KWVmXsmeDwgKUc0ZjhpmL0dgRDqaaBzjZE5ue3Qd2ifQNpUloV"
  # Get your credentials from: https://developer.twitter.com

# SportMonks API Configuration (Alternative/Additional)
sportmonks:
  api_key: "your_sportmonks_api_key_here"
  # Get your key from: https://www.sportmonks.com
