# Soccer Performance Intelligence System Configuration Template

# API Configuration
api_football:
  base_url: "https://v3.football.api-sports.io"
  timeout: 30
  rate_limit_delay: 1.0
  cache_enabled: true
  cache_duration_hours: 24

# OpenAI Configuration
openai:
  model: "gpt-4"
  temperature: 0.7
  max_tokens: 1000
  embedding_model: "text-embedding-ada-002"

# Data Collection Settings
data_collection:
  leagues:
    - id: 140  # La Liga
      name: "La Liga"
      country: "Spain"
    - id: 2    # Champions League
      name: "UEFA Champions League"
      country: "World"
  
  seasons:
    - 2023
    - 2022
  
  cache_directory: "data/raw"
  max_requests_per_minute: 100

# Data Processing Settings
data_processing:
  feature_engineering:
    include_advanced_metrics: true
    normalize_features: true
    handle_missing_values: "interpolate"
  
  output_directory: "data/processed"

# Analysis Settings
analysis:
  shapley:
    n_iterations: 1000
    confidence_level: 0.95
    features:
      - "goals"
      - "assists"
      - "passes_completed"
      - "tackles_won"
      - "interceptions"
      - "aerial_duels_won"
  
  tactical:
    formation_analysis: true
    player_positioning: true
    team_dynamics: true

# RAG System Settings
rag_system:
  vector_store:
    type: "chromadb"
    collection_name: "soccer_intelligence"
    embedding_dimension: 1536
  
  retrieval:
    top_k: 5
    similarity_threshold: 0.7
  
  generation:
    context_window: 4000
    response_length: 500

# Logging Configuration
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "logs/soccer_intelligence.log"

# Visualization Settings
visualization:
  style: "seaborn-v0_8"
  figure_size: [12, 8]
  dpi: 300
  save_format: "png"
