analysis:
  analysis_types:
  - Shapley Value Analysis
  - Tactical Formation Analysis
  - Performance Metrics
  - Multi-Competition Performance
  - Cross-League Comparison
  league_distribution:
    bundesliga: 8
    la_liga: 7
    ligue_1: 6
    premier_league: 7
    serie_a: 6
  priority_teams:
  - 85
  - 541
  - 157
  - 50
  - 550
  - 530
  - 571
  - 529
  - 165
  - 505
  - 173
  - 569
  - 496
  - 40
  - 211
  - 49
  - 194
  - 212
  - 536
  - 499
  - 492
  - 596
  - 33
  - 489
  - 645
  - 47
  - 553
  - 598
  - 620
  - 168
  - 597
  - 79
data:
  core_teams_count: 67
  focus_competitions:
  - UEFA Champions League
  - Premier League
  - La Liga
  - Serie A
  - Bundesliga
  - Ligue 1
  - UEFA Europa League
  - Domestic Cups (FA Cup, Copa del Rey, Coppa Italia, DFB-Pokal)
  mapped_teams_count: 34
  source_directory: data/focused
project:
  description: Focused analysis of Champions League teams across all competitions
  name: Soccer Performance Intelligence System - Champions League Focus
  scope: Champions League teams multi-competition analysis
  version: 2.0.0
system:
  cache_strategy: focused_teams_only
  data_filter: champions_league_teams
  focused_mode: true
  multi_competition_context: true
