# Comprehensive Team Statistics Collection Configuration
# For collecting team-level statistics and match details for 67 UEFA Champions League teams

project:
  name: "ADS599 Capstone - Team Statistics Collection"
  scope: "67 UEFA Champions League Teams"
  temporal_scope: "2019-2024 (6 seasons)"
  data_types: ["team_statistics", "match_details", "league_standings"]

# Collection Scope
collection_scope:
  # Target teams (extracted from roster files)
  teams:
    source: "data/focused/players/team_rosters/"
    extraction_method: "roster_file_parsing"
    core_teams_only: true
    expected_count: 67
    
  # Target seasons
  seasons:
    target_seasons: [2019, 2020, 2021, 2022, 2023, 2024]
    season_count: 6
    
  # Competition coverage
  competitions:
    primary:
      - id: 2
        name: "UEFA Champions League"
        type: "champions_league"
        priority: 1
      - id: 39
        name: "Premier League"
        type: "domestic_league"
        priority: 2
      - id: 140
        name: "La Liga"
        type: "domestic_league"
        priority: 2
      - id: 135
        name: "Serie A"
        type: "domestic_league"
        priority: 2
      - id: 78
        name: "Bundesliga"
        type: "domestic_league"
        priority: 2
      - id: 61
        name: "Ligue 1"
        type: "domestic_league"
        priority: 2
    
    secondary:
      - id: 3
        name: "UEFA Europa League"
        type: "europa_league"
        priority: 3
      - id: 48
        name: "FA Cup"
        type: "domestic_cup"
        priority: 4
      - id: 143
        name: "Copa del Rey"
        type: "domestic_cup"
        priority: 4
      - id: 137
        name: "Coppa Italia"
        type: "domestic_cup"
        priority: 4
      - id: 81
        name: "DFB Pokal"
        type: "domestic_cup"
        priority: 4
      - id: 66
        name: "Coupe de France"
        type: "domestic_cup"
        priority: 4

# Data Collection Requirements
data_requirements:
  # Team-level statistics
  team_statistics:
    required_fields:
      - "fixtures" # matches played, wins, draws, losses
      - "goals" # goals scored/conceded
      - "league_position" # final league position
      - "points" # total points earned
      - "clean_sheets" # clean sheet statistics
      - "cards" # yellow/red card statistics
    
    optional_fields:
      - "biggest_wins_losses" # biggest victories and defeats
      - "penalty_statistics" # penalty conversion rates
      - "lineups" # formation usage statistics
      - "home_away_split" # home vs away performance
  
  # Match details
  match_details:
    required_fields:
      - "fixture_id" # unique match identifier
      - "date" # match date and time
      - "teams" # home/away teams
      - "score" # final score
      - "result" # win/draw/loss from team perspective
      - "competition" # league/cup information
      - "venue" # stadium information
    
    optional_fields:
      - "match_statistics" # possession, shots, etc.
      - "lineups" # starting lineups and substitutions
      - "events" # goals, cards, substitutions
      - "referee" # match officials

# API Efficiency Configuration
api_efficiency:
  # Rate limiting
  rate_limiting:
    requests_per_minute: 100
    delay_between_requests: 0.6 # seconds
    delay_between_seasons: 1.0 # seconds
    delay_between_teams: 2.0 # seconds
    
  # Caching strategy
  caching:
    enabled: true
    cache_directory: "data/cache/team_statistics/"
    cache_expiry_days: 30
    avoid_duplicate_requests: true
    cache_by_team_season: true
    cache_by_league: true
    
  # Request optimization
  optimization:
    batch_requests: false # API doesn't support batching
    parallel_requests: false # Respect rate limits
    skip_existing_data: true
    use_cached_data: true

# Data Organization
data_organization:
  # Output structure
  output_structure:
    base_directory: "data/focused/teams/"
    team_directory_pattern: "team_{team_id}/"
    season_directory_pattern: "{season}/"
    file_naming_pattern: "team_{team_id}_statistics_{season}.json"
    
  # File format
  file_format:
    format: "json"
    encoding: "utf-8"
    indent: 2
    ensure_ascii: false
    
  # Data structure
  data_structure:
    root_fields:
      - "team_id"
      - "season"
      - "collection_timestamp"
      - "league_statistics"
      - "match_details"
      - "season_summary"
    
    league_statistics_structure:
      - "league_id"
      - "league_name"
      - "league_type"
      - "team_info"
      - "fixtures"
      - "goals"
      - "additional_stats"
    
    match_details_structure:
      - "fixture_id"
      - "date"
      - "league"
      - "teams"
      - "score"
      - "venue"
      - "statistics"

# Quality Assurance
quality_assurance:
  # Consistency targets
  consistency:
    minimum_percentage: 99.85
    validation_enabled: true
    error_threshold: 0.15
    
  # Coverage requirements
  coverage:
    team_coverage_target: 100.0 # percentage of 67 teams
    season_coverage_target: 100.0 # percentage of 6 seasons
    competition_coverage_minimum: 80.0 # percentage of competitions
    
  # Data validation
  validation:
    required_field_validation: true
    data_type_validation: true
    range_validation: true
    consistency_checks: true
    
  # Error handling
  error_handling:
    log_errors: true
    continue_on_error: true
    max_consecutive_errors: 10
    retry_failed_requests: true
    retry_attempts: 3

# Performance Targets
performance_targets:
  # Collection speed
  collection_speed:
    teams_per_hour: 8
    seasons_per_team_per_hour: 12
    api_requests_per_hour: 5000
    
  # Resource utilization
  resource_limits:
    max_api_requests_per_run: 8000
    max_collection_duration_hours: 12
    memory_limit_gb: 6
    disk_space_limit_gb: 2
    
  # Success metrics
  success_metrics:
    minimum_teams_collected: 60 # 90% of 67 teams
    minimum_seasons_per_team: 5 # 83% of 6 seasons
    minimum_matches_per_team_season: 20 # reasonable minimum

# Monitoring and Reporting
monitoring:
  # Progress tracking
  progress_reporting:
    enabled: true
    interval_teams: 5
    show_api_usage: true
    show_time_estimates: true
    show_cache_efficiency: true
    
  # Real-time monitoring
  real_time_monitoring:
    track_api_quota: true
    track_error_rates: true
    track_collection_speed: true
    alert_on_high_error_rate: true
    
  # Final reporting
  final_reports:
    collection_summary: true
    api_usage_report: true
    quality_validation: true
    team_coverage_report: true
    match_statistics_summary: true

# Integration Settings
integration:
  # Compatibility with existing systems
  compatibility:
    player_statistics_system: true
    shapley_analysis_framework: true
    validation_scripts: true
    
  # Data format consistency
  format_consistency:
    match_player_data_structure: true
    use_same_team_ids: true
    consistent_season_format: true
    compatible_json_structure: true
    
  # Analysis integration
  analysis_integration:
    enable_shapley_analysis: true
    support_multi_season_comparison: true
    provide_team_performance_metrics: true
    include_competition_specific_data: true
